name: MLP
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pip
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - polars
  - scikit-learn
  - scipy
  - tqdm
  - seaborn
  - optuna
  - pyro-ppl
  - sentence-transformers
  - gpytorch

  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu130
    - torch
    - torchvision
    - logparser3
    - "datasets>=2.20.0"
    